before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: oKaA6RFVRASINEYU56AhOQ4SqcqX+uWxeMNpMxE9tnF4dodWxmeLe30iarXZge6Y8BYCMLxiUswKhQgP3KcK4ulmJ/Z0hs+wqkOmcBUlVpdWUDs387pT+DAybeh2WPxZaJvdOpIuLvG3iF29kysBswqSYBpYmN9kieDm2S2woyF0wknSSHGn8V/NZoAjGyoHSaFSPD89mSGS2dhsw87Ieg//AbFdM/DB4ZhrgsTRndoHHOOvtg8jq419JvizhF26E3l0cqJbFnErHOFYQ03qlgbEnBzXQOfY7hYl/zqAyrNhkwsKd/MI/MPMNnkyifVAjiCa5hW72y5+JyVf0mWL19HPJwt1yTShfZUP5mFTxGOQTLO0y3MXJg1pGmpY93zCkGPMUqSNXA6iqtSaHo+JmfsWsHBkcfAXWMZDd+LzrA3/u2Rsv5RMWTk4r5sUWYkz0ROvpCbBHkCBTzG6z8DWCI40uueYfqFq4EJu9OHabr4AJ2l8CChBJCNVL7czJRhLwanLRjtXHw8gwwnFjAZP0lBQimne5AGLfIFeTnAUhW3+batwgmh9x1SZ79sdZxqLd1p9wt+gvYof36Yub0aOK8zCUlF2q9MCBXV2MDNtc1H5UI29IBjYNmRTvjbJCOJiL4N5AYQmpdmoUPv2y0MJNir/5nLMXDgasR+K29qEBtc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
